name = "hancut-concert"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# D1 데이터베이스 설정
[[d1_databases]]
binding = "DB"
database_name = "hancut-concert-db"
database_id = "e851631b-ae22-4c9c-b779-6421362c1a71"

